### ISSUE TITLE
issue with basicStats

### ISSUE THREAD

**Issue by ldutoit** [kkeenan02/diveRsity#11]
Hi,

thanks for a great package! I ma having issues running the basicStats function.
```
a<-readGenepop("testgenepop.txt") # file attached from http://genepop.curtin.edu.au/help_input.html
basicStats(a)
```
result in the following error:

```
Error in if (popLoc[1] == 3) { : missing value where TRUE/FALSE needed
```
I tried a couple of input files and always get the same error at the same exact position but I don't know what popLoc[1] is.

Could ypou maybe help us with this?

Cheers

Ludovic Dutoit
[testgenepop.txt](https://github.com/kkeenan02/diveRsity/files/3409172/testgenepop.txt)

**Comment by ldutoit** [comment]
My bad! I got it now, thanks :)

**Comment by uod12345** [comment]
Hi,

I'm having the same issue. How did you solve it? Please let me know.

**Comment by ldutoit** [comment]
Hi,

you actually need to give the function the file path as an argument and not
a matrix object.

Kind Regards

Ludo

**Comment by uod12345** [comment]
Oh alright! Thanks!

**Comment by uod12345** [comment]
Hi Ludo,

I'm trying to calculate pFST or P values for Fst per locus that I have calculated for variants in 2 populations. I'm trying to do a permutation based Fst and then obtain a CI or P value.I have tried a lot of methods from different R packages, but I'm not able to solve the problem. I'm not really a coder, and hence struggling with it. I have created a genepop file for DiverRsity, but the format doesn't seem to be right. I created it from Plink binary files > import as genlight > genind > genepop. 
Can you please help me with it? I have been trying for too long now. 

Regards,
Charvi

**Comment by ldutoit** [comment]
Hi Charvi,

I am not the developper of this package, I was just letting the user know how I solved this specific issue. TYour question is unrelated.

Kind Regards

Ludo

**Comment by uod12345** [comment]
Thanks Ludo. I know that you are not the developer of this package. I asked
the question since you have worked on a similar analysis.

Anyways, thank you.

Regards,
Charvi

**Comment by zdiazmar** [comment]
Hi Ludo,

I am having the same issue you described but I haven't been able to sort out a solution.

This is my code:
```
setwd("~/path/to/my/directory")
a<-readGenepop(infile = './myfile.txt', gp=3)
summary(a) # I get a correct summary of my genepop file
basicStats(infile = a, outfile = diversity, fis_ci = FALSE,
           ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL,
           mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05,
           fis_alpha = 0.05)
#or as you tried
basicStats(a)
```
And regardless I get the error:
```
Error in if (popLoc[1] == 3) { : missing value where TRUE/FALSE needed
```
I have also tried:
```
basicStats(infile = 'myfile.txt', outfile = diversity, fis_ci = FALSE,
           ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL,
           mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05,
           fis_alpha = 0.05)
```
And get a different error:
```
Error in out[match(names(args[[i]]), rownames(out)), i] <- as.numeric(args[[i]]) : 
  NAs are not allowed in subscripted assignments
```

Is this similar to the issue you had? If so, can you recommend a more detailed solution?

Thanks in advance,
Zoe

**Comment by ldutoit** [comment]
Hi Zoe,

the version where you give the file path to basicStats is on the right
track:

I would try it first without all your arguments:

```
basicStats(infile = 'myfile.txt')
```

the first one with basicStats(a) won't work.

That might likely not work, but I'd start there. One area I'd explore from
this error is simply the format of your genepop file. Do all loci have
names? Do individuals have names too? It is looking like it is trying to
match things out, so perhaps your file lack loci names, or individual names?

That is what I can do to help as I just used this package once and I am not
the developer.

Kind regards and I hope that helps

Ludo

On Tue, 5 May 2020 at 09:06, zdiazmar <notifications@github.com> wrote:
>
> Hi Ludo,
>
> I am having the same issue you described but I haven't been able to sort
out a solution.
>
> This is my code:
>
> setwd("~/path/to/my/directory")
> a<-readGenepop(infile = './myfile.txt', gp=3)
> summary(a) # I get a correct summary of my genepop file
> basicStats(infile = a, outfile = diversity, fis_ci = FALSE,
>            ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL,
>            mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05,
>            fis_alpha = 0.05)
> #or as you tried
> basicStats(a)
>
> And regardless I get the error:
>
> Error in if (popLoc[1] == 3) { : missing value where TRUE/FALSE needed
>
> I have also tried:
>
> basicStats(infile = 'myfile.txt', outfile = diversity, fis_ci = FALSE,
>            ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL,
>            mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05,
>            fis_alpha = 0.05)
>
> And get a different error:
>
> Error in out[match(names(args[[i]]), rownames(out)), i] <-
as.numeric(args[[i]]) :
>   NAs are not allowed in subscripted assignments
>
> Is this similar to the issue you had? If so, can you recommend a more
detailed solution?

**Comment by zdiazmar** [comment]
Thanks, Ludo! My code still isn't running, but I'll take a closer look at the genepop formatted file. I appreciate your response :)

**Comment by kwamebrain** [comment]
Hi ldutoit 
Please I experiencing similar problem and I have combed online for solution but to no avail. please bail me out if you can. Thanks in advance
x <- readGenepop(infile = "gam_data.txt", gp = 3, bootstrap = FALSE)
y <- basicStats(infile = x, outfile = basicstat, fis_ci = FALSE, ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL, mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05, fis_alpha = 0.05 )

Error in if (popLoc[1] == 3) { : missing value where TRUE/FALSE needed

**Comment by ldutoit** [comment]
Hi,
as stated in the discussion, you need to give the name file to basicStats
```
basicStats(infile = "gam_data.txt", outfile = basicstat, fis_ci = FALSE, ar_ci = FALSE, fis_boots = NULL, ar_boots = NULL, mc_reps = 9999, rarefaction = TRUE, ar_alpha = 0.05, fis_alpha = 0.05 )
```
hope that helps!
cheers
Ludo

**Comment by ElizaR27** [comment]
Hi, I have the same problem I am not sure if my format is correct (I convert a .vcf to .genepop.txt) with PGDspider so maybe something change 
Please I really need help 
data <- readGenepop(infile = "Tags_genepop.txt", gp = 3, bootstrap = FALSE)test_results <- basicStats(infile = "Tags_genepop.txt", outfile = "test_run1",
                           fis_ci = TRUE, ar_ci = TRUE, fis_boots = 999,
                           ar_boots = 999, mc_reps = 9999,
                           rarefaction = FALSE, ar_alpha = 0.05,
                           fis_alpha = 0.05)

[Uploading Tags_genepop.txt…]()
