### ISSUE TITLE
Problem with RAM

### ISSUE THREAD

**Issue by ottocapo** [kkeenan02/diveRsity#4]
Hi, I've been trying to use the diveRsity package to obtain the Fis values from a few populations based on approx. 5k SNPs. So far I havent been able to get any results because while running a pretty basic calculation like the divBasic, the process will use all the available ram (14gbs on my computer) and finally just show a ram allocation error. This could mean that there are some error on my file but it runs just fine on Genepop.
Cheers

**Comment by kkeenan02** [comment]
Hi,

This is strange. I have tested the function for > 500,000 SNPs, and it has run fine. To troubleshoot the issue I would need the data.

Alternatively, you could try the basicStats function, which has all of the functionality of divBasic + more.

KK
